services:
  web:
    build: ./chall
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=secret_bro_my_secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    restart: unless-stopped 
    shm_size: '1gb'